### ISSUE TITLE
Is maintaining a PeriodO-to-Palladio tool feasible or worthwhile?

### ISSUE THREAD

**Issue by rybesh** [zmbq/periodo-visualizations#17]
The prototype web app in this repository demonstrates how an arbitrary set of PeriodO periods can be visualized in Palladio.

Because visualizing PeriodO data in Palladio involves setting up two datasets (the periods to be visualized *and* the associated places) in a particular way, one cannot start with a single PeriodO CSV file and just "visualize" it in Palladio (which is the assumption the Palladio designers made about how it would be used).

The prototype gets around this by transforming the period data (and associated gazetteer data) into files in the undocumented "Palladio Save File" format, and then loading this data into the Palladio map component and timespan component (using some "wrapper" code which gets around the fact that Palladio was not designed to allow end-users to directly load "save files" in this way).

Given these workarounds, the way this was implemented is quite fragile. (This was not the fault of the implementors but is due to Palladio limitations.) It served the purpose of demonstrating that PeriodO data can be visualized in Palladio, but it isn't suitable for maintaining a tool over time.

The core problems are that:

1. Palladio has no officially supported file format for anything more complicated than basic tabular data, but PeriodO data is not tabular, nor can the basic period-to-place relationships be easily represented in a single table.
1. Palladio is a monolithic app not intended to be used as a library by other applications (which would make it easier to build a stable web app that uses the Palladio visualization components without fragile hacks).

Palladio is no longer under development and has only received security updates over the past couple of years. It seems unlikely that either of the core problems above will be addressed.

In the meantime, in the time since this prototype was first created, we added to the PeriodO client the ability to visualize the spatial and temporal coverage of arbitrary sets of periods—exactly what this prototype had enabled.

I can't find any working examples of Palladio map or timespan visualizations anywhere, but it might be worth looking for some to see if there is some aspect of them that is lacking in the PeriodO map and timespan visualizations. It would be far easier to enhance the PeriodO map and timespan visualizations then to get this prototype running again (and to keep it running over time).

Thoughts @atomrab?

**Comment by atomrab** [comment]
I have some Palladio visualizations that I'm adding [here](https://utexas.box.com/s/03m4ydqjz9co6ihz8ta14i36n59qii9o) -- Palladio json with time and points in space, and Palladio json representing PeriodO csv that I loaded just for the timelines. Load these into https://hdlab.stanford.edu/palladio/ to take a look.

The two particularly useful things Palladio can do that we currently can't are 1) filter by dragging over a span on the timeline (to focus on a particular area of interest) and 2) change the display logic according to different attributes of the data (though not to the point I'd hoped, where it would be possible to arrange a set of definitions in order of publication date). It's the user-defined dynamic component that I was hoping we could adopt -- the original idea was to do this using embedded (and static?) Palladio "bricks", so that we wouldn't have to run a whole local instance. There are examples of this at the Stanford Mapping the Republic of Letters project [here](http://republicofletters.stanford.edu/publications/voltaire/correspondents/) and [here](http://republicofletters.stanford.edu/publications/grandtour/education/).

Our current filtering is mainly text-based, and we don't have a good way to sort a bar chart by user preferences. I'd still really like to find a way to make it easier to compare the time-spans of all the "Archaic" periods, filter that set to show only the definitions that overlap with 600-500 BC, and then order those by authority date. It would also be preferable to be able to hover over a bar and see the label, for easier comparison (our visualization highlights a definition selected from the list, but that's harder for comparisons). I'd hoped that we could use the Palladio bricks for that, so that we wouldn't have to build or maintain it, but I see the issue with fragility.

The map component is the most complicated element, and I haven't tried to get polygons into Palladio, which is really more a point-based visualization. We might be able to get around this with centroids, but I'm not sure it's worth it. The real value for me is in greater user control over what shows up on a stacked-bar timeline, and flexibility in how that timeline can be ordered.
